Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on  computers  category
    And
    And
    Then i should able to see sub category for computers as Desktops ,Notebooks and Software


Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on  Electronics  category
    And
    And
    Then i should able to see sub category for Camera & photo ,Cellphones and others

Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on  Appreal category
    And
    And
    Then i should able to see sub category for Shoes ,Clothing and Accessories

Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on Digital downloads category
    And
    And
    Then i should able to see downloads products

Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on  Books category
    And
    And
    Then i should able to see select category for Sort by ,Display per Page

Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on  Jewelry category
    And
    And
    Then i should able to see select category for Sort by , Display per page

Feature: Varify Category page
  As a demo.nopcommerce.com user i should able to view all category

  Background:

  Scenario:user should able to see category page.
    Given As a user i m  on the demo.nopcommerce.com home page

    When i click on  Gift Cards category
    And
    And
    Then i should able to see select category for Sort by , Display per page






